/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sofi.operator.schemas;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** * A customer's banking information did not pass GIACT verification.
    * Note: GIACT is a company, not an acronym. */
@org.apache.avro.specific.AvroGenerated
public class GiactVerificationFailed extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6555346911164847966L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GiactVerificationFailed\",\"namespace\":\"com.sofi.operator.schemas\",\"doc\":\"* A customer's banking information did not pass GIACT verification.\\n    * Note: GIACT is a company, not an acronym.\",\"fields\":[{\"name\":\"partyId\",\"type\":\"long\",\"doc\":\"Party id (customer id) in Customers service\"}],\"version\":1}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GiactVerificationFailed> ENCODER =
      new BinaryMessageEncoder<GiactVerificationFailed>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GiactVerificationFailed> DECODER =
      new BinaryMessageDecoder<GiactVerificationFailed>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<GiactVerificationFailed> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<GiactVerificationFailed> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<GiactVerificationFailed>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this GiactVerificationFailed to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a GiactVerificationFailed from a ByteBuffer. */
  public static GiactVerificationFailed fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Party id (customer id) in Customers service */
   private long partyId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GiactVerificationFailed() {}

  /**
   * All-args constructor.
   * @param partyId Party id (customer id) in Customers service
   */
  public GiactVerificationFailed(java.lang.Long partyId) {
    this.partyId = partyId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return partyId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: partyId = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'partyId' field.
   * @return Party id (customer id) in Customers service
   */
  public java.lang.Long getPartyId() {
    return partyId;
  }

  /**
   * Sets the value of the 'partyId' field.
   * Party id (customer id) in Customers service
   * @param value the value to set.
   */
  public void setPartyId(java.lang.Long value) {
    this.partyId = value;
  }

  /**
   * Creates a new GiactVerificationFailed RecordBuilder.
   * @return A new GiactVerificationFailed RecordBuilder
   */
  public static com.sofi.operator.schemas.GiactVerificationFailed.Builder newBuilder() {
    return new com.sofi.operator.schemas.GiactVerificationFailed.Builder();
  }

  /**
   * Creates a new GiactVerificationFailed RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GiactVerificationFailed RecordBuilder
   */
  public static com.sofi.operator.schemas.GiactVerificationFailed.Builder newBuilder(com.sofi.operator.schemas.GiactVerificationFailed.Builder other) {
    return new com.sofi.operator.schemas.GiactVerificationFailed.Builder(other);
  }

  /**
   * Creates a new GiactVerificationFailed RecordBuilder by copying an existing GiactVerificationFailed instance.
   * @param other The existing instance to copy.
   * @return A new GiactVerificationFailed RecordBuilder
   */
  public static com.sofi.operator.schemas.GiactVerificationFailed.Builder newBuilder(com.sofi.operator.schemas.GiactVerificationFailed other) {
    return new com.sofi.operator.schemas.GiactVerificationFailed.Builder(other);
  }

  /**
   * RecordBuilder for GiactVerificationFailed instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GiactVerificationFailed>
    implements org.apache.avro.data.RecordBuilder<GiactVerificationFailed> {

    /** Party id (customer id) in Customers service */
    private long partyId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sofi.operator.schemas.GiactVerificationFailed.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.partyId)) {
        this.partyId = data().deepCopy(fields()[0].schema(), other.partyId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing GiactVerificationFailed instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sofi.operator.schemas.GiactVerificationFailed other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.partyId)) {
        this.partyId = data().deepCopy(fields()[0].schema(), other.partyId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'partyId' field.
      * Party id (customer id) in Customers service
      * @return The value.
      */
    public java.lang.Long getPartyId() {
      return partyId;
    }

    /**
      * Sets the value of the 'partyId' field.
      * Party id (customer id) in Customers service
      * @param value The value of 'partyId'.
      * @return This builder.
      */
    public com.sofi.operator.schemas.GiactVerificationFailed.Builder setPartyId(long value) {
      validate(fields()[0], value);
      this.partyId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'partyId' field has been set.
      * Party id (customer id) in Customers service
      * @return True if the 'partyId' field has been set, false otherwise.
      */
    public boolean hasPartyId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'partyId' field.
      * Party id (customer id) in Customers service
      * @return This builder.
      */
    public com.sofi.operator.schemas.GiactVerificationFailed.Builder clearPartyId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GiactVerificationFailed build() {
      try {
        GiactVerificationFailed record = new GiactVerificationFailed();
        record.partyId = fieldSetFlags()[0] ? this.partyId : (java.lang.Long) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GiactVerificationFailed>
    WRITER$ = (org.apache.avro.io.DatumWriter<GiactVerificationFailed>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GiactVerificationFailed>
    READER$ = (org.apache.avro.io.DatumReader<GiactVerificationFailed>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
